spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_recommend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    open-in-view: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug

naver:
  url:
    search:
      book: https://openapi.naver.com/v1/search/book.json

  client:
    id: 8itRfzoamOSgZ9tmpets
    secret: Dk22MR6Cbn

jwt:
  header: Authorization
  #HS512
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400 #1?